name: API Automation CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Upgraded to v4 to fix the Node.js warning!
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Upgraded to v4 and changed Java to 17 to fix the PlayStation error!
    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run API Tests via Maven
      run: mvn clean test